// Line-icon set using Lucide (ISC license)
// Icons inherit currentColor for easy theming in light/dark mode

export { DoorOpen as DoorIcon } from 'lucide-react'
export { DoorOpen as DoorOpenIcon } from 'lucide-react'
export { DoorClosed as DoorClosedIcon } from 'lucide-react'
export { KeyRound as KeyIcon } from 'lucide-react'
export { Footprints as StairsIcon } from 'lucide-react'
export { ArrowUpToLine as StairsUpIcon } from 'lucide-react'
export { ArrowDownToLine as StairsDownIcon } from 'lucide-react'
export { AlertTriangle as TrapIcon } from 'lucide-react'
export { CheckCircle2 as TrapDisarmedIcon } from 'lucide-react'
export { Skull as SkullIcon } from 'lucide-react'
export { Users as UsersIcon } from 'lucide-react'
export { Gem as GemIcon } from 'lucide-react'
export { Sparkles as SparklesIcon } from 'lucide-react'
export { Theater as MasksIcon } from 'lucide-react'
export { User as UserIcon } from 'lucide-react'
export { ChevronUp as ChevronUpIcon } from 'lucide-react'
export { ChevronDown as ChevronDownIcon } from 'lucide-react'
export { Copy as CopyIcon } from 'lucide-react'
export { Trash2 as TrashIcon } from 'lucide-react'
export { Plus as PlusIcon } from 'lucide-react'
export { Minus as MinusIcon } from 'lucide-react'
export { X as CloseIcon } from 'lucide-react'
export { GripVertical as GripIcon } from 'lucide-react'
export { SkipForward as NextTurnIcon } from 'lucide-react'
export { Heart as HeartIcon } from 'lucide-react'
export { Shield as ShieldIcon } from 'lucide-react'
export { Lock as LockIcon } from 'lucide-react'
export { LockOpen as UnlockIcon } from 'lucide-react'
export { EyeOff as HiddenIcon } from 'lucide-react'
export { LayoutGrid as RoomIcon } from 'lucide-react'
export { Package as ItemIcon } from 'lucide-react'
export { Package as PropIcon } from 'lucide-react'
export { Box as PropChestIcon } from 'lucide-react'
export { Table2 as PropTableIcon } from 'lucide-react'
export { Frame as PropMirrorIcon } from 'lucide-react'
export { Barrel as PropBarrelIcon } from 'lucide-react'
export { Landmark as PropStatueIcon } from 'lucide-react'
export { Eye as PerceptionIcon } from 'lucide-react'
export { Save as SaveIcon } from 'lucide-react'
export { ZoomIn as ZoomInIcon } from 'lucide-react'
export { ZoomOut as ZoomOutIcon } from 'lucide-react'
export { Maximize2 as FitIcon } from 'lucide-react'
export type { LucideIcon } from 'lucide-react'
